name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ios:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Build and test
        run: xcodebuild test -scheme SelectableText -destination 'platform=iOS Simulator,name=iPhone 14 Pro'

  test-macos:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Build and test
        run: xcodebuild test -scheme SelectableText -destination 'platform=macOS,arch=x86_64'

  test-visionos:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Build and test
        run: xcodebuild test -scheme SelectableText -destination 'platform=visionOS Simulator,name=Apple Vision Pro'
